import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const logs = [];
page.on("console", (m) => logs.push(`[${m.type()}] ${m.text().slice(0,200)}`));
page.on("pageerror", (e) => logs.push(`[pageerror] ${String(e).slice(0,200)}`));
page.on("requestfailed", (r) => logs.push(`[reqfail] ${r.url()} ${r.failure()?.errorText}`));
await page.addInitScript(() => window.localStorage.setItem("trova.setupComplete", "true"));
await page.goto("http://127.0.0.1:1420", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
await page.evaluate(async () => {
  await fetch("http://127.0.0.1:17654/api/command", { method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify({command:"start_indexing",args:{paths:[{id:"e2e",path:"/var/home/fabio/Documenti/Claude/Trova/.trova/test-fixtures/goal1-core",enabled:true,recursive:true,isExcluded:false,geminiEnabled:false,autoIndex:true,sourceType:"local"}]}}) });
});
const si = page.locator(".search-box input").first();
await si.fill("elefante"); await si.press("Enter");
await page.waitForTimeout(2000);
console.log("ask-row presente:", await page.locator(".local-ask-row input").count());
const ask = page.locator(".local-ask-row input").first();
await ask.fill("Ciao");
await page.locator(".local-ask-row button").first().click();
console.log("cliccato Chiedi, attendo 30s...");
await page.waitForTimeout(30000);
const chat = await page.locator(".local-chat-thread").innerText().catch(() => "(no thread)");
console.log("CHAT:", chat.slice(0, 300).replace(/\n/g," "));
await page.screenshot({ path: "/tmp/trova-e2e/chat-debug.png" });
console.log("--- LOGS ---");
console.log(logs.slice(-15).join("\n"));
await browser.close();
process.exit(0);
